### ISSUE TITLE
[IDENTITIES] reddit proofs fail signature verification

### ISSUE THREAD

**Issue by sudoWright** [keybase/keybase-issues#4227]
**New and existing IDENTITIES Reddit proofs failing**

Error on keybase client 6.2.5-20240101042619+3bdf76f84a
**UNREACHABLE**

Cannot maintain or create proofs with the Reddit web-service. 

![Screenshot 2024-01-04 at 12 20 18 PM](https://github.com/keybase/keybase-issues/assets/25876554/fd791cbc-30d5-44ea-9b77-5771f5811a63)

https://www.reddit.com/r/KeybaseProofs/ 
Unable to verify new Reddit proofs after they are posted in the proper forum. 

Error message from proof sig-verification response: 
"Your proof could not be found, and Keybase has stopped checking.
How would you like to proceed?"

**Comment by ForbiddenEra** [comment]
I'm having the same issue. Also with The Social Media Site Formerly Known as Twitter, aka Xwitter (pronounced Shitter ;) )

![image](https://github.com/keybase/keybase-issues/assets/7980490/5832e110-a8af-4ca6-add1-1057e3c7c241)

**Comment by AoSankaku** [comment]
Same here

**Comment by lucasfcnunes** [comment]
Same here.

### `403 Blocked`
```yaml
    result:
      proofId: 0
      proofResult:
        state: 2
        status: 240
        desc: 403 Blocked
      cached:
        proofResult:
          state: 2
          status: 240
          desc: 403 Blocked
        time: 1708644674874
        freshness: 0
```

### From:

```yaml
# keybase id -j | yq -P
username: lucasfcnunes
lastTrack: null
cryptocurrencies:
  # ...
stellar:
  # ...
identifyKey:
  pgpFingerprint: Ubu3GduaP4qSik1cnXa52OHiDpk=
  KID: 01013aaa70e0cf05be5e3304853e6437a240f97fcc213ec1a85e794da1c0d8cdb7fb0a
  breaksTracking: false
  sigID: 409a08e48d3baf6472e70a697a05e74a4f4e7794e4256671c0733c95d35a7e7d0f
proofs:
  # ...
  - proof:
      proofType: 4
      key: reddit
      value: pkmatador
      displayMarkup: pkmatador
      sigID: f570033485348f37f345613b8826805a9d4ef396a69d8c5ade9c817e49bd82840f
      mTime: 1568200205000
    result:
      proofId: 0
      proofResult:
        state: 2
        status: 240
        desc: 403 Blocked
      snoozedResult:
        state: 1
        status: 1
        desc: ""
      torWarning: false
      tmpTrackExpireTime: 0
      cached:
        proofResult:
          state: 2
          status: 240
          desc: 403 Blocked
        time: 1708644674874
        freshness: 0
      hint:
        remoteId: t3_d2ofx5
        humanUrl: https://www.reddit.com/r/KeybaseProofs/comments/d2ofx5/my_keybase_proof_redditpkmatador/
        apiUrl: https://www.reddit.com/r/KeybaseProofs/comments/d2ofx5/my_keybase_proof_redditpkmatador/.json
        checkText: hKRib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEg0A9cN/B7wWBGgRz/nZGsoHYvC5EG9XlX2S7A2j824fkKp3BheWxvYWTESpcCEMQgzhc8WzHMDb2C1tTOoxhPUeXhDI95QbjgzTl96asvo1jEIJM6HrNoNrmdLeN1TeBWMORXG0gBU5UihqM/OJlrzhTsAgHCo3NpZ8RAlByN+TgGBz5nigRrdYaHnEFsYGYEB/oc9YSaxjMo6xUvafzG4tTxJ4mzlUk90bkya8xVayxWxnWDkLIhG/VOAqhzaWdfdHlwZSCkaGFzaIKkdHlwZQildmFsdWXEIHOtY9eTREyR8CTaB3vVVFC6HIxYSkXy9ZHeOPISOf0Ko3RhZ80CAqd2ZXJzaW9uAQ==
      breaksTracking: false
```
